[package]
name = "ruminant"
version = "0.1.0"
edition = "2024"

[dependencies]
rhai = "1.21"
uuid = { version = "1.16", features = ["v7"] }
rand = "0.9"
rand_distr = "0.5"
parking_lot = "0.12"
statrs = "0.18"
itertools = "0.14"
clap = { version = "4.5", features = ["derive"] }
textplots = "0.8"
